# Generated by Django 5.2.8 on 2025-11-13 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('announcements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['created_at'], name='announcemen_created_40a59f_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['visible_until'], name='announcemen_visible_f81a96_idx'),
        ),
    ]
