# Generated by Django 5.2.8 on 2025-11-13 21:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('internship', 'Internship'), ('job', 'Job'), ('scholarship', 'Scholarship'), ('volunteer', 'Volunteer Work'), ('competition', 'Competition')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('deadline', models.DateField()),
                ('requirements', models.JSONField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['deadline'],
            },
        ),
    ]
